name: Build and Deploy to ECS

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.yaml'
      - '*.yml'
      - '.github/workflows/cloudformation.yml'
      - 'README.md'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY_URI : public.ecr.aws/i3g8s7k5/giftedlabs/tasksphere

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Configure AWS Credentials (Public ECR is in us-east-1, but your app is in eu-central-1)
      - name: Configure AWS Credentials for ECR Public
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      # Login to Amazon ECR Public
      - name: Login to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public


      # Build and push the image to ECR
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          docker build -t ${{ env.ECR_REPOSITORY_URI }}:${{ github.sha }} .
          docker tag ${{ env.ECR_REPOSITORY_URI }}:${{ github.sha }} ${{ env.ECR_REPOSITORY_URI }}:latest
          docker push ${{ env.ECR_REPOSITORY_URI }}:${{ github.sha }}
          docker push ${{ env.ECR_REPOSITORY_URI }}:latest
          echo "IMAGE_URI=${{ env.ECR_REPOSITORY_URI }}:${{ github.sha }}" >> $GITHUB_ENV